### PR TITLE
Laravel 8.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 8.x.

**Before merging**, you need to:

- Checkout the `l8-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/spatie/laravel-honeypot/pull/65/commits/5c30640bd372bba4a6e3bc68b48440b8885a7d02?w=1) for Laravel 8. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-honeypot.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "spatie/laravel-honeypot": "dev-l8-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by AlexVanderbist** [comment]
@jasonmccreary / @laravel-shift just a heads up: this PR seems to have bumped the minimum required Laravel version for this package instead of adding Laravel 8 support

**Comment by jasonmccreary** [comment]
Shift automatically detects this based on existing constraints. Since none of them were "appended", then it assumed it should not.

You can update this to append them manually and next time Shift will do the same.

**Pull request merged**
