### PR TITLE
SpamProtection to use the honeypot everywhere

### PR DESCRIPTION
**Pull request by masterix21**
It adds the ability to use the honeypot everywhere through a trait: for example, in a Livewire component.

I will add a test before the merge (if it will be approved).

### CODE REVIEW

**Comment by freekmurze** [comment]
Looks good, ping me again when tests have been added.

**Comment by masterix21** [comment]
@freekmurze

I replaced many code parts because my first version wasn't good for me. 

So, look at the `README.md` to understand how it works: I think this is the best solution to support the antispam in the Livewire components.

Tests are ready.

**Comment by freekmurze** [comment]
Thanks! I'll polish a bit on `main` and release it.

**Comment by masterix21** [comment]
❤️

**Comment by masterix21** [comment]
Do you have any idea about the release date? Thanks for all your effort.

**Comment by freekmurze** [comment]
O, I thought I already done that.

There you go: https://github.com/spatie/laravel-honeypot/releases/tag/4.3.0

Thanks again!

**Comment by francoism90** [comment]
@masterix21 @freekmurze Maybe this can be added to the README? By using an extra trait, it can be included with ease into every component with minimal code:

```php
<?php

namespace App\Traits;

use Spatie\Honeypot\Http\Livewire\Concerns\HoneypotData;
use Spatie\Honeypot\Http\Livewire\Concerns\UsesSpamProtection;

trait WithHoneypot
{
    use UsesSpamProtection;

    public HoneypotData $extraFields;

    public function mountWithHoneypot()
    {
        $this->extraFields = new HoneypotData();
    }
}
```

e.g. signup
```php
<?php

use App\Traits\WithHoneypot;

class SignupComponent extends Component
{
    use WithHoneypot;

    public function submit()
    {
        // Protect against spam
        $this->protectAgainstSpam();

        // Validate request
        $validated = $this->validate();

       // ..
    }
}

**Comment by freekmurze** [comment]
@francoism90 Feel free to PR that to the readme.

**Comment by masterix21** [comment]
@francoism90: I didn't create a trait like yours only to randomize the forms better, but as Freek said, feel free to PR it (I'm not a maintainer here, so I can't help you).

**Pull request merged**
