### PR TITLE
Added Carbon 3 to the requirements

### PR DESCRIPTION
**Pull request by poldixd**
With laravel 11 you can use carbon 2 or 3: https://laravel.com/docs/11.x/upgrade#carbon-3

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by jonathan-bird** [comment]
@freekmurze I found that with Carbon 3, it throws an Exception if you set `HONEYPOT_SECONDS=1` in the .env file as it casts the value to a string. If you publish the config file and set 1 as an integer there, no worries.

Potentially worth casting to an integer when calling `$this->config['amount_of_seconds']`?

The exception is (essentially saying amount of seconds value is string, rather than int/float):
```
Carbon\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 324
```

**Comment by freekmurze** [comment]
Feel free to PR this 👍

**Comment by clementmas** [comment]
@jonathan-bird this type issue has been fixed in the latest version of this package. See https://github.com/spatie/laravel-honeypot/pull/131

**Pull request merged**
